### ISSUE TITLE
Please darken the purple border (body CSS background color)

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/tools-for-habitica#1]
https://github.com/HabitRPG/tools-for-habitica/blob/05953412eee0d4b99344aae5e849588561e1325d/tools.css#L4

The purple used for the background of the body is *incredibly* harsh and is triggering a sensory disability of mine something awful. (It makes sense it's very bright as it's the same color as the attention-getting underline highlight in the navbar on the website.) Any way it could be changed, perhaps to something like #36205d (the color of the part of the site header that contains the avatars) or #432874 (the color of the website's navbar)? That may make it less prone to causing accessibility issues for disabilities like mine. (The light blue of the original tool was even better to me as it was very inobtrusive, but considering I'm assuming the change to purple was an attempt to be "on brand" I'm not sure there's a light purple that the maintainers of this fork would consider sufficiently "Habitica". IDK.)

**Comment by phillipthelen** [comment]
When choosing colors for the Habitica website and associated tools, we try to account for various accessibility needs while also aiming to adhere to contrast guidelines. While we are aware of the varying degrees of accessibility, we understand that it is not possible to be accessible for everyone. If you can point us towards resources about the particular disability you mentioned, it can help us balance our decisions with other users' needs.

**Comment by citrusella** [comment]
That body color is not serving as a background to text, it's behind the part that is. It would be completely possible to change it to a more muted (or at least darker) color in its use in the body CSS without it affecting WCAG contrast compliance anywhere else. Before originally reporting this, I even fought what the color was doing to me in order to check *every* page of the tool to be sure the color was used *nowhere else* and also that there were not other pressing accessibility issues with the CSS. The darker brand colors I provided would only serve to maintain or improve contrast ratios *if* there's a place where compliant-contrast text exists on that body color background in the tool, as any such text would have to *lighter* than that purple since the darkest possible text results in a ratio that fails AA.

I tried searching for resources that I thought would explain it better (or in different words) than I did, particularly in the context of web design, but I didn't find one I thought would be adequate to link here. Let's put it this way: It makes it nearly impossible for me to use the tool because I can't actually keep enough of my attention on the content (dependent on other input I'm getting at around the same time I've even gotten headaches from it). The color currently in use is like... the strobe light of Habitica brand colors to my brain, which makes sense because its function within the website is to highlight something.

I hope that all makes sense.

**Comment by citrusella** [comment]
Any updates?

**Comment by phillipthelen** [comment]
We were taking some time to look into this on our side as well.

For some context, we chose one of our brighter purples to create a more energetic feel that some sources claim can stimulate the brain to help creativity and focus. However, we know this is not universal and that colors can create different experiences for different people. With this in mind, we’ve decided to close this issue with the option to reopen it pending more documentation.

While we can’t create a single design that works for everyone, we completely encourage creating a 3rd party extension to edit the colors to fit your needs.

**Comment by citrusella** [comment]
I guess I thought the change I suggested would serve to make the tool usable to the largest amount of people without people having to know how to code (or know how to find someone who knows how to code) in order to make it possible for them to use the tool.

I'll probably just use Alys' version of the tool since it's still available/working and is already accessible to me. 🙃 Has the added benefit of my not having to break my comrade retirement to write new CSS.

Thanks.
